version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_static_data: {}
  production_media_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: lexmapr_django_production_django
    depends_on:
      - postgres
      - redis
    volumes:
      - production_static_data:/app/lexmapr_django/static
      - production_media_data:/app/lexmapr_django/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    expose:
      - "5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lexmapr_django_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "5432:5432"

#  traefik:
#    build:
#      context: .
#      dockerfile: ./compose/production/traefik/Dockerfile
#    image: lexmapr_django_production_traefik
#    depends_on:
#      - django
#    volumes:
#      - production_traefik:/etc/traefik/acme
#    ports:
#      - "0.0.0.0:80:80"
#      - "0.0.0.0:443:443"

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: lexmapr_django_production_nginx
    depends_on:
      - django
    volumes:
      - production_static_data:/app/lexmapr_django/static
      - production_media_data:/app/lexmapr_django/media
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: lexmapr_django_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: lexmapr_django_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: lexmapr_django_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
#  awscli:
#    build:
#      context: .
#      dockerfile: ./compose/production/aws/Dockerfile
#    env_file:
#      - ./.envs/.production/.django
#    volumes:
#      - production_postgres_data_backups:/backups
