# Generated by Django 2.1.8 on 2019-08-16 22:46

from django.db import migrations, models
import lexmapr_django.pipeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False)),
                ('input_file', models.FileField(blank=True, upload_to='input_files/')),
                ('output_file', models.FileField(blank=True, upload_to='output_files/')),
                ('expires', models.DateTimeField(default=lexmapr_django.pipeline.models.get_expiry_date)),
                ('err', models.BooleanField(default=False)),
                ('err_msg', models.TextField(blank=True)),
            ],
        ),
    ]
