# Generated by Django 2.1.8 on 2019-08-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20190814_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='err',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinejob',
            name='err_msg',
            field=models.TextField(blank=True),
        ),
    ]
