
FROM python:3.6-alpine

ENV PYTHONUNBUFFERED 1

RUN apk update \
  # psycopg2 dependencies
  && apk add --virtual build-deps gcc python3-dev musl-dev \
  && apk add postgresql-dev \
  # Pillow dependencies
  && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
  # CFFI dependencies
  && apk add libffi-dev py-cffi \
  # Install git so we can install the original LexMapr repository as a
  # package in requirements.txt.
  && apk add git \
  # Needed to run commands as django user
  && apk add --no-cache su-exec

RUN addgroup -S django \
    && adduser -S -G django django

# Requirements are installed here to ensure they will be cached.
COPY ./requirements /requirements
RUN pip install --no-cache-dir -r /requirements/production.txt \
    && rm -rf /requirements

# Set up LexMapr. Need to install LexMapr locally for now.
# TODO: When LexMapr is updated to cache resources in folder with
#  global write permissions, we can do a global install.
ENV PATH "$PATH:/home/django/.local/bin"
RUN su-exec django pip install --user --no-cache-dir git+https://github.com/Public-Health-Bioinformatics/LexMapr#egg=LexMapr
RUN for i in 1 2 3 4 5 6 7 8; do su-exec django python -m nltk.downloader all && break || sleep 15; done
COPY ./first_time_run.csv /first_time_run.csv
COPY ./envo_foodon_config.json /envo_foodon_config.json
RUN su-exec django lexmapr first_time_run.csv -c envo_foodon_config.json -b

COPY ./compose/production/django/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint
RUN chown django /entrypoint

COPY ./compose/production/django/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start
RUN chown django /start
COPY ./compose/production/django/celery/worker/start /start-celeryworker
RUN sed -i 's/\r$//g' /start-celeryworker
RUN chmod +x /start-celeryworker
RUN chown django /start-celeryworker

COPY ./compose/production/django/celery/beat/start /start-celerybeat
RUN sed -i 's/\r$//g' /start-celerybeat
RUN chmod +x /start-celerybeat
RUN chown django /start-celerybeat

COPY ./compose/production/django/celery/flower/start /start-flower
RUN sed -i 's/\r$//g' /start-flower
RUN chmod +x /start-flower
COPY . /app

RUN chown -R django /app

USER django

WORKDIR /app

ENTRYPOINT ["/entrypoint"]
